### ISSUE TITLE
error: macro names must be identifiers

### ISSUE THREAD

**Issue by PGlyre** [dimamedia/filament-spool-scale#1]
I have a problem, and I probably do not understand because I am a beginner. I get an error when I upload a sketch and I don't have the knowledge to understand what I'm missing

**spool-scale:18:9: error: macro names must be identifiers
 #define 250_FILAMENT  250 // 250g filament
         ^~~~~~~~~~~~
spool-scale:19:9: error: macro names must be identifiers
 #define 500_FILAMENT  500 // 500g filament
         ^~~~~~~~~~~~
exit status 1
macro names must be identifiers**

I have full respect if you cannot or do not want to help me because I am convinced that it is my knowledge that is not enough

**Comment by dimamedia** [comment]
Macro should start with a letter, not number. Some IDEs doesn't check that. Updated the source with corrected marcos.
